/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelhokleyton;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Carlos
 */
public class FrameJogoVelha extends javax.swing.JFrame {

    /**
     * Creates new form FrameJogoVelha
     *
     */
    int res[][] = new int[4][4];
    boolean vez;
    int player1 = 0, player2 = 0, contagem = 0, total = 0;

    public FrameJogoVelha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCalculadora = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPlacar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPlacar2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanelCalculadora.setBackground(new java.awt.Color(0, 204, 102));

        jPanel2.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabelPlacar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelPlacar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlacar1.setText("0");
        jPanel2.add(jLabelPlacar1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jPanel2.add(jLabel2);

        jLabelPlacar2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelPlacar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlacar2.setText("0");
        jPanel2.add(jLabelPlacar2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JOGADOR 1");
        jPanel3.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JOGADOR 2");
        jPanel3.add(jLabel5);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);

        jButton31.setBackground(new java.awt.Color(255, 255, 255));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);

        jButton32.setBackground(new java.awt.Color(255, 255, 255));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);

        jButton33.setBackground(new java.awt.Color(255, 255, 255));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);

        jProgressBar1.setMaximum(10);

        javax.swing.GroupLayout jPanelCalculadoraLayout = new javax.swing.GroupLayout(jPanelCalculadora);
        jPanelCalculadora.setLayout(jPanelCalculadoraLayout);
        jPanelCalculadoraLayout.setHorizontalGroup(
            jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        jPanelCalculadoraLayout.setVerticalGroup(
            jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculadoraLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(361, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        this.vez(jButton33, 3, 3);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.vez(jButton12, 1, 2);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.vez(jButton11, 1, 1);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        this.vez(jButton13, 1, 3);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.vez(jButton21, 2, 1);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.vez(jButton22, 2, 2);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        this.vez(jButton23, 2, 3);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        this.vez(jButton31, 3, 1);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        this.vez(jButton32, 3, 2);
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void vez(JButton bt, int linha, int coluna) {
        //revebe botao,linha e coluna
        if (this.vez && this.res[linha][coluna] == 0) {//se for verdadeiro é a vez do X 
            bt.setBackground(Color.DARK_GRAY);
            bt.setForeground(Color.RED);
            bt.setText("X");
            this.res[linha][coluna] = 1;//criar uma matriz e definir x=1 na matriz
            this.contagem++;//contagem para caso de velha
            vez = !vez;
        } else if (!this.vez && this.res[linha][coluna] == 0) {//se for falso é a vez do O
            bt.setBackground(Color.DARK_GRAY);
            bt.setForeground(Color.GREEN);
            bt.setText("O");
            this.res[linha][coluna] = 100;
            this.contagem++;
            vez = !vez;
        }
        verificar();
    }

    public void verificar() {//fazer a verificacao atravez de matriz

        int somaDp = 0, somaDs = 0;
        for (int i = 1; i <= 3; i++) {
            somaDp += res[i][i];
            somaDs += res[i][4 - i];
            int somaLinha = 0, somaColuna = 0;
            for (int j = 1; j <= 3; j++) {
                somaLinha += res[i][j];
                somaColuna += res[j][i];
            }
            if (somaLinha == 3 || somaColuna == 3) {
                this.player1++;
                limpar();
            } else if (somaLinha == 300 || somaColuna == 300) {
                this.player2++;
                limpar();
            }
        }
        if (somaDp == 3 || somaDs == 3) {
            this.player1++;
            limpar();
        } else if (somaDp == 300 || somaDs == 300) {
            this.player2++;
            limpar();
        }
        if (this.contagem == 9 && this.res[1][1] != 0) {
            limpar();
        }

    }

    public void limpar() {
        //cada rodada limpa os campos,a matriz e acrescenta +1 ao total
        this.total++;
        if (this.total == 10) {
            if(this.player1>this.player2){
                JOptionPane.showMessageDialog(null,"O player 1 GANHOU");
            }else if(this.player1<this.player2){
                JOptionPane.showMessageDialog(null,"O player 2 GANHOU");
            }else{JOptionPane.showMessageDialog(null,"Empate");}
            jLabelPlacar1.setText("");
            jLabelPlacar2.setText("");
            this.total = 0;
        } else {
            jLabelPlacar2.setText(String.valueOf(this.player2));
            jLabelPlacar1.setText(String.valueOf(this.player1));
        }

        jProgressBar1.setValue(this.total);
        this.vez = true;
        this.contagem = 0;
        for (int i = 1; i <= 3; i++) {
            for (int j = 1; j <= 3; j++) {
                res[i][j] = 0;
            }
        }
        

        jButton11.setBackground(Color.WHITE);
        jButton11.setForeground(Color.BLACK);
        jButton11.setText("");

        jButton12.setBackground(Color.WHITE);
        jButton12.setForeground(Color.BLACK);
        jButton12.setText("");

        jButton13.setBackground(Color.WHITE);
        jButton13.setForeground(Color.BLACK);
        jButton13.setText("");

        jButton21.setBackground(Color.WHITE);
        jButton21.setForeground(Color.BLACK);
        jButton21.setText("");

        jButton22.setBackground(Color.WHITE);
        jButton22.setForeground(Color.BLACK);
        jButton22.setText("");

        jButton23.setBackground(Color.WHITE);
        jButton23.setForeground(Color.BLACK);
        jButton23.setText("");

        jButton31.setBackground(Color.WHITE);
        jButton31.setForeground(Color.BLACK);
        jButton31.setText("");

        jButton32.setBackground(Color.WHITE);
        jButton32.setForeground(Color.BLACK);
        jButton32.setText("");

        jButton33.setBackground(Color.WHITE);
        jButton33.setForeground(Color.BLACK);
        jButton33.setText("");

    }
    
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJogoVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPlacar1;
    private javax.swing.JLabel jLabelPlacar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCalculadora;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
